version: "3"

services:
  nginx: 
    image: mapic/shiny-nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx.certbot.conf:/etc/nginx/nginx.certbot.conf
      - ./ssl/:/home/ssl/
    ports:
      - "80:80"
      - "443:443"
    env_file: config/nginx.env
    command: "bash docker-entrypoint.sh"

  auth0:
    image: mapic/shiny-auth0:latest
    env_file: config/auth0.env
    # command: "npm start"
    volumes:                              # for debug only
      - ../shiny-auth0/app/:/usr/src/app  # for debug only
    command: "bash docker-entrypoint.sh"  # for debug only

  shiny:
    image: mapic/shiny-server-pro:latest
    env_file: config/shiny.env
    volumes:
      - ./config/shiny-server.conf:/etc/shiny-server/shiny-server.conf

networks:
  default:
    external:
      name: shiny-network  
