version: "3"

services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "8443:443"
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/nginx.conf && cat /etc/nginx/nginx.conf && exec nginx -c /etc/nginx/nginx.conf"
    command: "nginx -c /etc/nginx/nginx.conf"

  auth0:
    # build: https://github.com/mapic/shiny-auth0.docker.git
    image: mapic/shiny-auth0
    volumes:
      - ./auth0.env:/usr/src/app/auth0.env
    command: "npm start"

  shiny:
    image: mapic/shiny-server-pro
    volumes:
      - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
    environment:
      - SHINY_LICENSE_PORT=8979
      - SHINY_LICENSE_SERVER=shiny-floating-license-server


networks:
  default:
    external:
      name: shiny-network  
