version: "3"

services:
  nginx: 
    image: mapic/shiny-nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx.certbot.conf:/etc/nginx/nginx.certbot.conf
      - ./ssl/:/home/ssl/
    ports:
      - "80:80"
      - "443:443"
    env_file: config/nginx.env
    # environment:
    #   - CERTBOT_DOMAIN=cloud.ngi.no
    #   - CERTBOT_EMAIL=knutole@mapic.io
    command: "bash docker-entrypoint.sh"

  auth0:
    image: mapic/shiny-auth0:latest
    env_file: config/auth0.env
    command: "npm start"

  shiny:
    image: mapic/shiny-server-pro:latest
    env_file: config/shiny.env
    volumes:
      - ./config/shiny-server.conf:/etc/shiny-server/shiny-server.conf
    # environment:
    #   - SHINY_LICENSE_PORT=8979
    #   - SHINY_LICENSE_SERVER=shiny-floating-license-server


networks:
  default:
    external:
      name: shiny-network  
