version: "3"

services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    command: "nginx -c /etc/nginx/nginx.conf"

  auth0:
    image: mapic/shiny-auth0:latest
    environment:
      - AUTH0_CLIENT_SECRET=myCoolSecret
      - AUTH0_CLIENT_ID=myCoolClientId
      - AUTH0_DOMAIN=myCoolDomain
      - AUTH0_CALLBACK_URL=https://my.url.com/
      - COOKIE_SECRET=somethingRandomHerePlease
      - SHINY_HOST=localhost
      - SHINY_PORT=3838
      - PORT=3000
    command: "npm start"

  shiny:
    image: mapic/shiny-server-pro:latest
    volumes:
      - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
    environment:
      - SHINY_LICENSE_PORT=8979
      - SHINY_LICENSE_SERVER=shiny-floating-license-server


networks:
  default:
    external:
      name: shiny-network  
